In [1]:
from conllu import parse
from io import open
from conllu import parse_incr
import numpy as np
import tensorflow.keras as keras

In [2]:
path = 'hi_hdtb-ud-train.conllu'

NameError: name 'data_file' is not defined

In [10]:
data_file = open("hi_hdtb-ud-dev.conllu", "r", encoding="utf-8")
sentences=[]
for tokenlist in parse_incr(data_file):
    sentences.append(tokenlist)

In [11]:
len(sentences)

1659

In [12]:
train

NameError: name 'train' is not defined

In [13]:
sen.text

NameError: name 'sen' is not defined

In [14]:

lis1 = []
for sen in train:
    lis = []
#     print(sen.text)
    for token in sen:
#         print(dir(token))
        lis.append(( token.lemma, token.upos))
#         break
#     print(dir(sen))
    lis1.append(lis)

NameError: name 'train' is not defined

In [15]:
train_sentences = sentences[:1500]
test_sentences = sentences[1500:]
data_hn=[[(token['form'],token['upostag']) for token in sentence ]for sentence in sentences ]

In [16]:
data_hn[0]
train_data_hn = data_hn[:1500]
test_data_hn = data_hn[1500:]

In [17]:
print(len(train_data_hn))

1500


In [18]:
sentences, sentence_tags =[], []

In [19]:
for tagged_sentence in lis1:
    sentence, tags = zip(*tagged_sentence)
    sentences.append(np.array(sentence))
    sentence_tags.append(np.array(tags))

In [20]:

words, tags = set([]), set([])
for data in data_hn:
    for form,tag in data:
        tags.add(tag)

for data in train_data_hn:
    for form,tag in data:
        words.add(form)

word2index = {w: i + 1 for i, w in enumerate(list(words))}
tag2index = {t: i + 1 for i, t in enumerate(list(tags))}
word2index['-OOV-']=0
tag2index['UNK']=0

In [21]:
word2index

{'७०': 1,
 'बांग्लादेश': 2,
 'समारोह': 3,
 'हाथ': 4,
 'कोफी': 5,
 'घोषित': 6,
 '५६०': 7,
 'लहर': 8,
 'दी': 9,
 'द्रविड़': 10,
 'पुंछ': 11,
 'मिग': 12,
 'नवांशहर': 13,
 'हासिल': 14,
 'ठप': 15,
 'अखिल': 16,
 'प्रदक्षिणा': 17,
 'कुंबले': 18,
 'कार्रवाई': 19,
 'ठंडा': 20,
 'कालोनी': 21,
 'हेतु': 22,
 'संस्\u200dथा': 23,
 'कसया': 24,
 'सालों': 25,
 'आलम': 26,
 'कड़ी': 27,
 'खादों': 28,
 'शेयरों': 29,
 'इकोनॅमिक्स': 30,
 'वाराणसी': 31,
 'नाइट्रेट': 32,
 'फुरसत': 33,
 'अनेकों': 34,
 'भड़क': 35,
 'तसवीर': 36,
 'पूछने': 37,
 'ईमानदारी': 38,
 'रोशनी': 39,
 '२००३': 40,
 'स्थिति': 41,
 'रिश्तेदारों': 42,
 'श्रद्धांजलि': 43,
 'विमान': 44,
 'मतभेद': 45,
 'बयान': 46,
 'खुफिया': 47,
 'अनलिमिटेड': 48,
 'वहां': 49,
 'फाइनेंस': 50,
 'सबक': 51,
 'पूर्वी': 52,
 'आतंकवाद': 53,
 'फैक्स': 54,
 'अनुभव': 55,
 'फायर': 56,
 'बढ़ेगी': 57,
 'अप्रसन्नता': 58,
 'ट्रस्ट': 59,
 'गाल': 60,
 'इंस्टीटयूट': 61,
 'सैर': 62,
 'आकर्षण': 63,
 'सरल': 64,
 '२००८': 65,
 'अवैध': 66,
 'दो': 67,
 'बालकृष्ण': 68,
 'भले': 69,
 'किमी':

In [22]:
len(word2index)
# word2index['-OOV-']

4989

In [23]:
test_sentences_X , test_tags_y = [] , []
for s in test_data_hn:
    s_int = [] 
    for w,_ in s:
        try:
            s_int.append(word2index[w]) 
        except KeyError:
            s_int.append(word2index['-OOV-'])
    test_tags_y.append([tag2index[t] for _,t in s])
    test_sentences_X.append(s_int)



In [24]:
test_sentences_X[0]

[1486,
 2760,
 2968,
 44,
 4100,
 0,
 844,
 2363,
 3240,
 2306,
 2679,
 1234,
 3160,
 2890,
 75,
 298,
 3160,
 47,
 3934,
 4542,
 1258,
 982,
 4100,
 4091,
 0,
 4542,
 1438,
 417,
 27,
 1906,
 9,
 1332,
 4913,
 4609]

In [47]:
train_sentences_X , train_tags_y = [] , []
for s in train_data_hn:
    s_int = [] 
    for w,_ in s:
        try:
            s_int.append(word2index[w]) 
        except KeyError:
            s_int.append(word2index['-OOV-'])
    train_tags_y.append([tag2index[t] for _,t in s])
    train_sentences_X.append(s_int)



In [48]:
train_sentences_X_unpad=train_sentences_X

In [26]:
train_sentences_X[0]
train_tags_y[0]

[15,
 15,
 11,
 3,
 15,
 11,
 3,
 15,
 11,
 3,
 15,
 11,
 15,
 15,
 15,
 15,
 11,
 1,
 14,
 3,
 11,
 11,
 4,
 13]

In [27]:
print(train_sentences_X[0], train_tags_y[0])

[1480, 3048, 351, 4334, 1442, 4100, 2231, 4987, 3160, 2603, 1478, 2306, 1421, 2703, 1058, 3116, 2525, 2292, 2155, 522, 4100, 434, 3269, 4609] [15, 15, 11, 3, 15, 11, 3, 15, 11, 3, 15, 11, 15, 15, 15, 15, 11, 1, 14, 3, 11, 11, 4, 13]


In [73]:
m=0
for i in train_sentences_X:
    m = max(m,max(i))
m

4988

In [74]:
MAX_LENGTH = len(max(train_sentences_X,key=len))

from keras.preprocessing.sequence import pad_sequences
train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')

In [75]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation
from tensorflow.keras.optimizers import Adam

In [76]:
model = Sequential() 
model.add(InputLayer(input_shape=(MAX_LENGTH, ))) 
model.add(Embedding(len(word2index), 128)) 
model.add(Bidirectional(LSTM(256, return_sequences=True))) 
model.add(TimeDistributed(Dense(len(tag2index)+1))) 
model.add(Activation('softmax')) # we compile the model 

model.compile(loss='categorical_crossentropy', optimizer=Adam(0.001), metrics=['accuracy'])

In [77]:
train_sentences_X[0]

array([1480, 3048,  351, 4334, 1442, 4100, 2231, 4987, 3160, 2603, 1478,
       2306, 1421, 2703, 1058, 3116, 2525, 2292, 2155,  522, 4100,  434,
       3269, 4609,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0], dtype=int32)

In [78]:
from keras.utils import to_categorical
cat_train_tags_y = to_categorical(train_tags_y, len(tag2index)+1) 

In [79]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)+1), batch_size=128, epochs=40, validation_split=0.2)

Train on 1200 samples, validate on 300 samples
Epoch 1/40
1200/1200 [==============================] - 7s 6ms/sample - loss: 1.9252 - accuracy: 0.6171 - val_loss: 0.9951 - val_accuracy: 0.6893
Epoch 2/40
1200/1200 [==============================] - 5s 4ms/sample - loss: 0.9764 - accuracy: 0.7104 - val_loss: 0.9572 - val_accuracy: 0.7029
Epoch 3/40
1200/1200 [==============================] - 4s 4ms/sample - loss: 0.8780 - accuracy: 0.7268 - val_loss: 0.8026 - val_accuracy: 0.7538
Epoch 4/40
1200/1200 [==============================] - 5s 4ms/sample - loss: 0.7827 - accuracy: 0.7607 - val_loss: 0.7557 - val_accuracy: 0.7871
Epoch 5/40
1200/1200 [==============================] - 5s 4ms/sample - loss: 0.7342 - accuracy: 0.7756 - val_loss: 0.7393 - val_accuracy: 0.7550
Epoch 6/40
1200/1200 [==============================] - 5s 4ms/sample - loss: 0.6944 - accuracy: 0.7730 - val_loss: 0.6934 - val_accuracy: 0.7777
Epoch 7/40
1200/1200 [==============================] - 5s 4ms/sample - loss:

In [101]:
def logits_to_tokens(sequences, index): 
    token_sequences = [] 
    for categorical_sequence in sequences: 
        token_sequence = [] 
        for cate in categorical_sequence: 
            token_sequence.append(index[np.argmax(cate)]) 
        token_sequences.append(token_sequence) 
    return token_sequences

In [81]:
tag2index.items()

dict_items([('PRON', 1), ('AUX', 2), ('NOUN', 3), ('VERB', 4), ('SCONJ', 5), ('CCONJ', 6), ('NUM', 7), ('DET', 8), ('ADV', 9), ('PART', 10), ('ADP', 11), ('X', 12), ('PUNCT', 13), ('ADJ', 14), ('PROPN', 15), ('UNK', 0)])

In [82]:
# train_sentences_X[:2]

In [91]:
predictions = model.predict(train_sentences_X[:2]) 

In [92]:
[len(i) for i in train_tags_y[:2]]

[68, 68]

In [93]:
[len(i) for i in train_sentences_X_unpad[:20]]

[24, 15, 19, 27, 12, 23, 4, 14, 15, 8, 11, 13, 17, 9, 11, 13, 10, 38, 18, 11]

In [94]:
(train_tags_y[:2])

array([[15, 15, 11,  3, 15, 11,  3, 15, 11,  3, 15, 11, 15, 15, 15, 15,
        11,  1, 14,  3, 11, 11,  4, 13,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 3, 11,  3,  4, 11, 11,  3, 11,  8,  3, 11, 14,  3,  4, 13,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=int32)

In [95]:
def index_to_tokens(sequences, index): 
    token_sequences = [] 
    for categorical_sequence in sequences: 
        token_sequence = [] 
        for cate in categorical_sequence: 
            token_sequence.append(index[cate]) 
        token_sequences.append(token_sequence) 
    return token_sequences

In [97]:
cor = index_to_tokens(train_tags_y[:2], {i: t for t, i in tag2index.items()})
cor

[['PROPN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'PROPN',
  'PROPN',
  'PROPN',
  'PROPN',
  'ADP',
  'PRON',
  'ADJ',
  'NOUN',
  'ADP',
  'ADP',
  'VERB',
  'PUNCT',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK'],
 ['NOUN',
  'ADP',
  'NOUN',
  'VERB',
  'ADP',
  'ADP',
  'NOUN',
  'ADP',
  'DET',
  'NOUN',
  'ADP',
  'ADJ',
  'NOUN',
  'VERB',
  'PUNCT',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
  'UNK',
 

In [102]:
predictions

array([[[3.6948809e-06, 2.2207301e-04, 6.0066277e-06, ...,
         1.4503231e-02, 9.7138458e-01, 2.3513994e-06],
        [3.2543307e-06, 1.4829625e-03, 4.2024822e-06, ...,
         4.5913385e-04, 7.7065653e-01, 1.0883774e-06],
        [8.0203552e-07, 5.8434023e-07, 8.9412751e-08, ...,
         6.1499365e-03, 1.8170990e-02, 3.2864097e-07],
        ...,
        [9.9999976e-01, 1.0108343e-08, 8.8858210e-09, ...,
         5.1880804e-08, 3.5794653e-18, 9.6106935e-11],
        [9.9999976e-01, 1.2411368e-08, 7.0147972e-09, ...,
         6.6917572e-08, 5.9439937e-18, 1.6664044e-10],
        [9.9999976e-01, 1.5892772e-08, 6.1031349e-09, ...,
         9.8438754e-08, 1.1798788e-17, 3.0492719e-10]],

       [[2.3683793e-05, 6.6777193e-03, 2.7740818e-06, ...,
         1.9167927e-03, 2.9951658e-03, 6.0401442e-07],
        [2.4939750e-06, 1.7970170e-07, 7.7279147e-08, ...,
         6.0011158e-03, 6.2887848e-05, 1.2414272e-07],
        [2.9255291e-06, 1.1443870e-04, 1.6755283e-07, ...,
         5.494

In [103]:
predictions
ans=logits_to_tokens(predictions, {i: t for t, i in tag2index.items()})

In [100]:
ans =[ans[i][:len(train_sentences_X_unpad[i])] for i,j in enumerate(ans)]
ans


[['PROPN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'PROPN',
  'PROPN',
  'PROPN',
  'PROPN',
  'ADP',
  'PRON',
  'ADJ',
  'NOUN',
  'ADP',
  'ADP',
  'VERB',
  'PUNCT'],
 ['PROPN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'PROPN',
  'PROPN',
  'PROPN'],
 ['PROPN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'PROPN',
  'PROPN',
  'PROPN',
  'PROPN',
  'ADP',
  'PRON',
  'ADJ'],
 ['PROPN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'PROPN',
  'PROPN',
  'PROPN',
  'PROPN',
  'ADP',
  'PRON',
  'ADJ',
  'NOUN',
  'ADP',
  'ADP',
  'VERB',
  'PUNCT',
  'UNK',
  'UNK',
  'UNK'],
 ['PROPN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP',
  'NOUN',
  'PROPN',
  'ADP'],
 ['PROPN',
  'PR

In [119]:
scores = model.evaluate(train_sentences_X, to_categorical(train_tags_y, len(tag2index)+1))

1500/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================